website/auth.py
from fileinput import filename
from flask import Flask, request, render_template, send_from_directory, send_file
import os
import cv2
import pathlib
import patoolib
from PIL import Image
import tensorflow as tf
tf.compat.v1.enable_eager_execution()
from tensorflow.python.keras import backend as K
#import segmentation_models
import segmentation_models as sm
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import *
import segmentation_models as sm

from flask import Blueprint, render_template, request, flash
def parse_image(filename, resize = True):
  '''
  Reads an image from a file,
  decodes it into a dense tensor,
  and resizes it to a fixed shape
  '''
  image = tf.io.read_file(filename)
  image = tf.image.decode_jpeg(image, channels=1)
  image = tf.image.convert_image_dtype(image, tf.float32)
  if resize:
    image = tf.image.resize(image, [128, 128])
  return image

def dice_coef(y_true, y_pred, smooth=K.epsilon()):
  y_true_f = K.flatten(y_true)
  y_pred_f = K.flatten(y_pred)
  intersection = K.sum(y_true_f * y_pred_f)
  return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)
dependencies = {'dice_coef':dice_coef, 'dice_loss':sm.losses.dice_loss }


def predict(file_path):
  '''
  Takes image path and returns input image and Predicted mask
  '''
  image = parse_image(file_path, resize = True)
  test1 = tf.data.Dataset.from_tensor_slices([image])
  
  #linking model
  link = os.path.join(APP_ROOT, 'model/')
  vein = "/".join([link, 'VeinModel.h5'])
  
  # Loading best model
  model = tf.keras.models.load_model(vein, custom_objects=dependencies)
  for image in test1.take(1):
    pred_mask1 = model.predict(image[tf.newaxis, ...])[0]
  return image, pred_mask1

def predict2(file_path):
  '''
  Takes image path and returns input image and Predicted mask
  '''
  image = parse_image(file_path, resize = True)
  test1 = tf.data.Dataset.from_tensor_slices([image])
  
  #linking model
  link = os.path.join(APP_ROOT, 'model/')
  thrombus = "/".join([link, 'ThrombusModel2.h5'])
  
  # Loading best model
  model = tf.keras.models.load_model(thrombus, custom_objects=dependencies)
  for image in test1.take(1):
    pred_mask1 = model.predict(image[tf.newaxis, ...])[0]
  return image, pred_mask1

def changeImageSize(maxWidth, 
                    maxHeight, 
                    image):
    
    widthRatio  = maxWidth/image.size[0]
    heightRatio = maxHeight/image.size[1]

    newWidth    = int(widthRatio*image.size[0])
    newHeight   = int(heightRatio*image.size[1])

    newImage    = image.resize((newWidth, newHeight))
    return newImage

app = Flask(__name__)

APP_ROOT = os.path.dirname(os.path.abspath(__file__))


auth = Blueprint('auth', __name__)


@auth.route('/UploadImage', methods = ['GET','POST'])
def uploadimage():
     data = request.form
     print(data)
     return render_template("index.html")
 
@auth.route('/UploadImage2', methods = ['GET','POST'])
def uploadimage2():
     data = request.form
     print(data)
     return render_template("indexthrom.html")

@auth.route('/UploadVideo', methods = ['GET','POST'])
def uploadvideo():
    data = request.form
    print(data)
    return render_template("indexvideo.html")

@auth.route('/EditImage', methods = ['GET','POST'])
def edit():

    return render_template("ImageEditor.html")

@auth.route('/test', methods = ['GET','POST'])
def testing():

     return render_template("zzztest.html")



filename = ''
@auth.route("/upload", methods=["POST"])
def upload():
    target = os.path.join(APP_ROOT, 'static/upload/')

    # create image directory if not found
    if not os.path.isdir(target):
        os.mkdir(target)

    # retrieve file from html file-picker
    upload = request.files.getlist("file")[0]
    print("File name: {}".format(upload.filename))
    global filename
    filename = upload.filename

    # file support verification
    ext = os.path.splitext(filename)[1]
    if (ext == ".jpg") or (ext == ".png") or (ext == ".bmp") or (ext == ".jpeg"):
        print("File accepted")
    else:
        return render_template("error.html", message="The selected file is not supported"), 400

    # save file
    destination = "/".join([target, filename])
    print("File saved to to:", destination)
    upload.save(destination) 
    
    destination = "/".join([target, 'test_image.jpg'])
    upload.save(destination) 


    # forward to processing page
    return render_template("processing.html", image_name = filename)

@auth.route("/upload2", methods=["POST"])
def upload2():
    target = os.path.join(APP_ROOT, 'static/upload/')

    # create image directory if not found
    if not os.path.isdir(target):
        os.mkdir(target)

    # retrieve file from html file-picker
    upload = request.files.getlist("file")[0]
    print("File name: {}".format(upload.filename))
    global filename
    filename = upload.filename

    # file support verification
    ext = os.path.splitext(filename)[1]
    if (ext == ".jpg") or (ext == ".png") or (ext == ".bmp") or (ext == ".jpeg"):
        print("File accepted")
    else:
        return render_template("error.html", message="The selected file is not supported"), 400

    # save file
    destination = "/".join([target, filename])
    print("File saved to to:", destination)
    upload.save(destination) 
    
    destination = "/".join([target, 'test_image.jpg'])
    upload.save(destination) 


    # forward to processing page
    return render_template("processingthrom.html", image_name = filename)

@auth.route("/uploadvideo2", methods=["POST"])
def upload3():
    target = os.path.join(APP_ROOT, 'static/video/')

    # create image directory if not found
    if not os.path.isdir(target):
        os.mkdir(target)

    # retrieve file from html file-picker
    upload = request.files.getlist("file")[0]
    print("File name: {}".format(upload.filename))
    global filename
    filename = upload.filename

    # file support verification
    ext = os.path.splitext(filename)[1]
    if (ext == ".avi") or (ext == ".mp4"):
        print("File accepted")
    else:
        return render_template("error.html", message="The selected file is not supported"), 400

    # save file
    destination = "/".join([target, filename])
    print("File saved to to:", destination)
    upload.save(destination)
    
    target = os.path.join(APP_ROOT, 'static/video/')
    destination = "/".join([target, filename])
    print(destination)
#    data_dir = pathlib.Path(target)
    
    vidcap = cv2.VideoCapture(destination)
    success,image = vidcap.read()
    count = 0
    i = 0

    while success:
        cv2.imwrite(os.path.join(target, "frame%d.jpg") % count, image)     # save frame as JPEG file      
        success,image = vidcap.read()
        print('Read a new frame: ', success)
        count += 1

    listFile = []
    for i in range(count):
        listFile.append(os.path.join('website/static/video/', 'frame{}.jpg'.format(i)))
        
        
    print(listFile)
    
    destination = "/".join([target, 'compressVideo.rar'])
    if os.path.isfile(destination):
        os.remove(destination)
    patoolib.create_archive(os.path.join(target, 'compressVideo.rar'), listFile)

    # forward to processing page
    return render_template("processingvideo.html", video_name = filename)


# Image segmentation
@auth.route("/Predic", methods=["POST"])
def Predict():
    
    # open and process image
    global filename
    target = os.path.join(APP_ROOT, 'static/upload/')
    destination = "/".join([target, filename])
    print(destination)
#    data_dir = pathlib.Path(target)
    file_path = destination
    
    img = Image.open(destination)

    image1, pred_mask1 = predict(file_path)
    image = tf.keras.preprocessing.image.array_to_img(image1)
    mask = tf.keras.preprocessing.image.array_to_img(pred_mask1)
    pred = Image.blend(image, mask, alpha=0.8)
    final = changeImageSize(img.size[0], img.size[1], pred)

    # save and return image
    destination = "/".join([target, 'temp1.png'])
    if os.path.isfile(destination):
        os.remove(destination)
    final.save(destination)

    send_image('temp1.png')
    
    # forward to processing page
    return render_template("predict.html", image_name = filename)

@auth.route("/Predic2", methods=["POST"])
def Predict2():
    
    # open and process image
    global filename
    target = os.path.join(APP_ROOT, 'static/upload/')
    destination = "/".join([target, filename])
    print(destination)
#    data_dir = pathlib.Path(target)
    file_path = destination
    
    img = Image.open(destination)

    image1, pred_mask1 = predict2(file_path)
    image = tf.keras.preprocessing.image.array_to_img(image1)
    mask = tf.keras.preprocessing.image.array_to_img(pred_mask1)
    pred = Image.blend(image, mask, alpha=20)
    final = changeImageSize(img.size[0], img.size[1], pred)

    # save and return image
    destination = "/".join([target, 'temp1.png'])
    if os.path.isfile(destination):
        os.remove(destination)
    final.save(destination)
    

    send_image('temp1.png')
    # forward to processing page
    return render_template("predict.html", image_name = filename)

# retrieve file from 'static/images' directory
@auth.route('/static/upload/<filename>')
def send_image(filename):
    return send_from_directory("static/upload", filename)

@auth.route('/static/video/<filename>')
def send_video(filename):
    return send_from_directory("static/video", filename)

@auth.route('/download')
def download_file():
	path = 'static/upload/temp1.png'
	return send_file(path, as_attachment=True)

@auth.route('/downloadoriginal')

website/templates/error.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Upload Vein</title>
    <link href="../static/css/index.css" rel="stylesheet"/>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="../static/css/all.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body class="bg-custom">
    <nav>
      <div class="logo">BloodSegmentation</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn">
      <ul>
        <li><a href="/EditImage">Crop Image</a></li>
        <li>
          <label for="btn-1" class="show">Features +</label>
          <a href="#">Select Segmentation</a>
          <input type="checkbox" id="btn-1">
          <ul>
            <li><a href="/UploadImage1">Vein</a></li>
            <li><a href="/UploadImage2">Thrombus</a></li>
          </ul>
        </li>
        <li>
          <label for="btn-2" class="show">Services +</label>
          <a href="#">Download</a>
          <input type="checkbox" id="btn-2">
          <ul>
            <li>
              <label for="btn-3" class="show">More +</label>
              <a href="#">Help <span class="fa fa-plus"></span></a>
              <input type="checkbox" id="btn-3">
              <ul>
                <li><a href="#">Latest</a></li>
                <li><a href="#">Processed</a></li>
                <li><a href="#">Item</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for('.download_file') }}">Photo</a></li>
            <li><a href="{{ url_for('.download_video') }}">Video</a></li>
          </ul>
        </li>
        <li><a href="/UploadVideo">Upload Video</a></li>
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
    <div class="content">
      <header>Invalid Upload</header>
      <p>Please Upload corresponding File with This Extension .jpg .png .bmp .jpeg
      </p>

      <form id="upload-form" action="{{ url_for('auth.upload') }}" method="POST" enctype="multipart/form-data">
        <input id="file-picker" type="file" name="file" accept="image/*" class="hidden" onchange="this.form.submit()">
        <label for="file-picker" class="btn btn-lg btn-success btn2">Select file</label>
      </form>

    </div>
    <script>
      $('.icon').click(function(){
        $('span').toggleClass("cancel");
      });
    </script>

  </body>
</html>

website/templates/index copy.html
<link href="../static/css/jumbotron-narrow.css" rel="stylesheet"/>
<link href="../static/css/style.css" rel="stylesheet"/>
<link href="../static/css/dropdown.css" rel="stylesheet"/>

<link
rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
crossorigin="anonymous"
/>

<link
rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
crossorigin="anonymous"
/>


<!DOCTYPE html>
<html lang="en">
 
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />


<head>
    <title>Python Flask Image Segmentation App</title>
 
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
 
</head>

 
<body class="back1">

    <div class="dropdown">
        <div class = "select">
          <span class = "selected">Select Segmentation</span>
          <div class = "caret"></div>
        </div>
        <ul class="menu">
          <li><a href="">Vein Segmentation</li>
          <li><a href="/UploadImage2">Thrombus Segmentation</li>
        </ul>
      </div>

    <div class="container">
        <div class="header">
            <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation" class="posisihilang"><a href="/"></a>
                    </li>
                    <li role="presentation" class="active btn posisi"><a href="/">Home Page</a>
                    </li>
                    <li role="presentation" class="active btn posisi"><a href="/UploadVideo">Upload Video</a>
                    </li>
                </ul>
            </nav>
            <h3 class="text-muted fonto">Vein Segmentation</h3>
        </div>
 
        <div class="jumbotron">
            <h1>Upload Image Here</h1>
            <p class="lead"></p>

	       <form id="upload-form" action="{{ url_for('auth.upload') }}" method="POST" enctype="multipart/form-data">
                <input id="file-picker" type="file" name="file" accept="image/*" class="hidden" onchange="this.form.submit()">
                <label for="file-picker" class="btn btn-lg btn-success btn2">Select file</label>
		    </form>
        </div>
 
    </div>


</body>
 
</html>

<script
type="text/javascript"
src="../static/javascr/dropdown.js"
></script>

website/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>Upload Vein</title>
    <link href="../static/css/index.css" rel="stylesheet"/>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="../static/css/all.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>


  <body class="bg-custom">

    <nav>
      <div class="logo">Thrombus Segmentation</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn">
      <ul>
        <li><a href="/EditImage">Crop Image</a></li>
        <li>
          <label for="btn-1" class="show">Segmentation</label>
          <a href="#">Select Segmentation</a>
          <input type="checkbox" id="btn-1">
          <ul>
            <li><a href="#">Vein</a></li>
            <li><a href="/UploadImage2">Thrombus</a></li>
          </ul>
        </li>
        <li><a href="/UploadVideo">Upload Video</a></li>
        <li>
          <label for="btn-2" class="show">Downlaod</label>
          <a href="#">Download</a>
          <input type="checkbox" id="btn-2">
          <ul>
            <li>
              <label for="btn-3" class="show">Help</label>
              <a href="/test">Help <span class="fa fa-plus"></span></a>
              <input type="checkbox" id="btn-3">
              <ul>
                <li><a href="#">Latest</a></li>
                <li><a href="#">Processed</a></li>
                <li><a href="#">Item</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for('.download_file') }}">Photo</a></li>
            <li><a href="{{ url_for('.download_video') }}">Video</a></li>
          </ul>
        </li>
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
    <div class="content">
      <header>Vein Segmentation</header>
      <!-- <h2>*For Thrombus Segmentation use "Select Segmentation" menu above.</h2> -->
      <p>Segmentation uses a deep learning method, namely U-Net. The application is able to be used to segment the area of vein in the interactive manner.
      </p>

      <form id="upload-form" action="{{ url_for('auth.upload') }}" method="POST" enctype="multipart/form-data">
        <input id="file-picker" type="file" name="file" accept="image/*" class="hidden" onchange="this.form.submit()">
        <label for="file-picker" class="bbtn">Select Image</label>
      </form>
    </div>

    <div class="content2">
      <p>The uploaded image is a zoomed image of blood vessels on an ultrasound image.
      </p>
      <img src="../static/images/tutorvein2.png">
    </div>




    <script>
      $('.icon').click(function(){
        $('span').toggleClass("cancel");
      });
    </script>

  </body>
</html>

website/templates/indexthrom.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Upload Thrombus</title>
    <link href="../static/css/index.css" rel="stylesheet"/>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="../static/css/all.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body class="bg-custom">
    <nav>
      <div class="logo">BloodSegmentation</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn">
      <ul>
        <li><a href="/EditImage">Crop Image</a></li>
        <li>
          <label for="btn-1" class="show">Segmentation</label>
          <a href="#">Select Segmentation</a>
          <input type="checkbox" id="btn-1">
          <ul>
            <li><a href="/UploadImage">Vein</a></li>
            <li><a href="/UploadImage2">Thrombus</a></li>
          </ul>
        </li>
        <li><a href="/UploadVideo">Upload Video</a></li>
        <li>
          <label for="btn-2" class="show">Downlaod</label>
          <a href="#">Download</a>
          <input type="checkbox" id="btn-2">
          <ul>
            <li>
              <label for="btn-3" class="show">Help</label>
              <a href="/test">Help <span class="fa fa-plus"></span></a>
              <input type="checkbox" id="btn-3">
              <ul>
                <li><a href="#">Latest</a></li>
                <li><a href="#">Processed</a></li>
                <li><a href="#">Item</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for('.download_file') }}">Photo</a></li>
            <li><a href="{{ url_for('.download_video') }}">Video</a></li>
          </ul>
        </li>
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
    <div class="content">
      <header>Thrombus Segmentation</header>
      <p>Segmentation uses a deep learning method, namely U-Net. The application is able to be used to segment the area of thrombus from vein in the interactive manner.
      </p>

      <form id="upload-form" action="{{ url_for('auth.upload2') }}" method="POST" enctype="multipart/form-data">
        <input id="file-picker" type="file" name="file" accept="image/*" class="hidden" onchange="this.form.submit()">
        <label for="file-picker" class="bbtn">Select Image</label>
      </form>
    </div>
    
    <div class="content2">
      <p>The uploaded image is a zoomed image of vein on an ultrasound image.
      </p>
      <img src="../static/images/tutorthrom.png">
    </div>

    </div>
    <script>
      $('.icon').click(function(){
        $('span').toggleClass("cancel");
      });
    </script>

  </body>
</html>

website/templates/indexvideo.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>Upload Vein</title>
    <link href="../static/css/indexvid.css" rel="stylesheet"/>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="../static/css/all.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>


  <body>
    
    <nav>
      <div class="logo">BloodSegmentation</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn">
      <ul>
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
    <div class="content">
      <header>Extract Images from Video</header>
      <p>Convert Video to Image Frame by Frame. Accepted Video are mp4 and avi.
      </p>

      <form id="upload-form" action="{{ url_for('auth.upload3') }}" method="POST" enctype="multipart/form-data">
        <input id="file-picker" type="file" name="file" accept="video/*" class="hidden" onchange="this.form.submit()">
        <label for="file-picker" class="bbtn" style="color:white;font-size:18px;">Select Video File</label>
      </form>
    </div>

    <div class="content2">
      <img src="../static/images/tutorvid2.png">
    </div>




    <script>
      $('.icon').click(function(){
        $('span').toggleClass("cancel");
      });
    </script>

  </body>
</html>

website/templates/predict.html
<link href="../static/css/result.css" rel="stylesheet"/>

<!DOCTYPE html>
<html lang="en">
<meta http-equiv="pragma" content="no-cache" />
 
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />

<head>
    <title>Predicted Image</title>
    <link href="../static/css/index.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
</head>
 
<body class = "back1 boxtu">  
    <nav>
        <div class="logo">BloodSegmentation</div>
        <label for="btn" class="icon">
          <span class="fa fa-bars"></span>
        </label>
        <input type="checkbox" id="btn">
        <ul>
          <li><a href="/UploadImage">Upload Again</a></li>
          <li><a href="/">Home</a></li>
        </ul>
    </nav>

      <script>
        $('.icon').click(function(){
          $('span').toggleClass("cancel");
        });
      </script>
 
      <div class="container">
					
        <div class="card">
          <div class="imgBx">
            <a href="{{ url_for('.download_file') }}">
              <img src="static/upload/temp1.png?modified=<? filemtime("static/upload/temp1.png")?">
            </a>
          
            <h2 style="color:white">Segmentation Result</h2>
            <p style="color:white"><br>Segmented Image
            </p>
            
          </div>
        </div>
      
        <div class="card">
          <div class="imgBx">
            <a href="{{ url_for('.download_original') }}">
              <img src="{{url_for('auth.send_image', filename=image_name)}} " style="max-width: 560px;">
            </a>
            <h2 style="color:white">Original image</h2>
            <p style="color:white"><br>*Click on Image to Download
            </p>					
  
          </div>	
        </div>
      </div>
</body>
 
</html>

website/templates/processing.html
<link href="../static/css/jumbotron-narrow.css" rel="stylesheet"/>
<link href="../static/css/style.css" rel="stylesheet"/>

<!DOCTYPE html>
<html lang="en">
 

<meta http-equiv="pragma" content="no-cache" />
 
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />

<head>
    <title>Process your image</title>
 
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
 
    <link href="../static/jumbotron-narrow.css" rel="stylesheet">

    <link href="../static/style.css" rel="stylesheet">
    
    <link href="../static/css/index.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
</head>
 
<body class = "back1 boxtu">

    <nav>
        <div class="logo">Preview Image</div>
        <label for="btn" class="icon">
          <span class="fa fa-bars"></span>
        </label>
        <input type="checkbox" id="btn">
        <ul>
          <li><a href="/UploadImage">Upload Again</a></li>
          <li><a href="/">Home</a></li>
        </ul>
    </nav>

      <script>
        $('.icon').click(function(){
          $('span').toggleClass("cancel");
        });
      </script>
 
    <div class="container">
 
        <div class="row marketing">
            
            <div class="col-lg-6">
                <form id="form-Predict" action="{{ url_for('auth.Predict') }}" method="POST" enctype="multipart/form-data">        
                  <button id="btnPredictV" class="btn btn-lg btn-success btn2" type="submit" name="mode" value="Predict">Predict</button>
                  	  <input type="text" class="hidden" name="image" value="{{ image_name }}">  

                </form>

            <h4 style="color:#1b1b1b">Click on predict to Run the model</h4>
            </div>
        </div>

        <div class="jumbotron">
		 <div id="image-container">
            <img src=" {{url_for('auth.send_image', filename=image_name)}} " style="max-width: 560px;">
            </div>
        </div>
 
    </div>
</body>
 
</html>

website/templates/processingthrom.html
<link href="../static/css/jumbotron-narrow.css" rel="stylesheet"/>
<link href="../static/css/style.css" rel="stylesheet"/>

<!DOCTYPE html>
<html lang="en">
 

<meta http-equiv="pragma" content="no-cache" />
 
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />

<head>
    <title>Process your image</title>
 
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
 
    <link href="../static/jumbotron-narrow.css" rel="stylesheet">

    <link href="../static/style.css" rel="stylesheet">
    
    <link href="../static/css/index.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
</head>
 
<body class = "back1 boxtu">

    <nav>
        <div class="logo">Preview Image</div>
        <label for="btn" class="icon">
          <span class="fa fa-bars"></span>
        </label>
        <input type="checkbox" id="btn">
        <ul>
          <li><a href="/UploadImage2">Upload Again</a></li>
          <li><a href="/">Home</a></li>
        </ul>
    </nav>

      <script>
        $('.icon').click(function(){
          $('span').toggleClass("cancel");
        });
      </script>
 
    <div class="container">
 
        <div class="row marketing">
            
            <div class="col-lg-6">
                <form id="form-Predict" action="{{ url_for('auth.Predict2') }}" method="POST" enctype="multipart/form-data">        
                  <button id="btnPredictV" class="btn btn-lg btn-success btn2" type="submit" name="mode" value="Predict">Predict</button>
                  	  <input type="text" class="hidden" name="image" value="{{ image_name }}">  

                </form>

            <h4 style="color:#1b1b1b">Click on predict to Run the model</h4>
            </div>
        </div>

        <div class="jumbotron">
		 <div id="image-container">
            <img src=" {{url_for('auth.send_image', filename=image_name)}} " style="max-width: 560px;">
            </div>
        </div>
 
    </div>
</body>
 
</html>

website/templates/processingvideo.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>Upload Vein</title>
    <link href="../static/css/indexvid.css" rel="stylesheet"/>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link href="../static/css/all.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>


  <body>
    
    <nav>
      <div class="logo">BloodSegmentation</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn">
      <ul>
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
    <div class="content">
      <header>Video Have Been Converted!</header>
      <p>Convert Video to Image Frame by Frame.
      </p>

      <div>
        <a href="{{ url_for('.download_video') }}">
          <button class="bbtn" style="color:white;font-size:18px;"> Download </button>
        </a>
      </div>
    </div>


    <script>
      $('.icon').click(function(){
        $('span').toggleClass("cancel");
      });
    </script>

  </body>
</html>